language: node_js
sudo: required
services:
  - docker
node_js:
  - "8"
before_script:
  - npm install
script:
  - npm run test
  - npm run lint
  - npm run build
  - docker build -t tsears/auth-api .
